spring:
    application:
        name: gateway-server
    main:
        web-application-type: reactive
        allow-bean-definition-overriding: true
    
    cloud:
        gateway:
            routes:
                -   id: user-microservice
                    uri: lb://users-microservice
                    predicates:
                        - Path=/users/**
                        - Path=/auth/**
                -   id: simulation-microservice
                    uri: lb://simulation
                    predicates:
                        - Path=/query/banks/**
                        - Path=/command/banks/**
                        - Path=/query/credits/**
                        - Path=/command/credits/**
                -   id: Rendez-Vous-microservice
                    uri: lb://Rendez-Vous
                    predicates:
                        - Path=/api/command/rendezvous/**
                        - Path=/api/query/rendezvous/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true