spring:
    application:
        name: gateway-server
    main:
        web-application-type: reactive
        allow-bean-definition-overriding: true
    
    cloud:
        gateway:
            routes:
                -   id: user-microservice
                    uri: lb://users-microservice
                    predicates:
                        - Path=/users/**
                        - Path=/auth/**

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
            register-with-eureka: true
            fetch-registry: true